name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }} -a
      - name: Clonar repositorio
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }} -a
      - name: Instalar packages
        run: npm i
      - name: Building...
        run: npm run build
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }} -a
      - run: echo "Valor de SALUDO ${{ secrets.SALUDO }}"

      - name: FTP Deployer
        uses: sand4rt/ftp-deployer@v1.4
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }} # FTP username
          password: ${{ secrets.FTP_PASSWORD }} # FTP password
          local_folder: '.' # optional, local path, default is: dist
          cleanup: false # optional, remove existing files inside FTP remote folder
          include: '[".output", "index.js"]' # optional, e.g. '['dist']'
          exclude: '[]' # optional, e.g. '['node_modules/**', '.git/**', '*.env']'
          #pasive: true # optional