name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }} -a
      - name: Clonar repositorio
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }} -a
      - name: Instalar packages
        run: npm i
      - name: Building...
        run: npm run build
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }} -a
      - run: echo "Valor de SALUDO ${{ secrets.SALUDO }}"

      - name: FTP Deployer
        uses: sand4rt/ftp-deployer@v1.4
        with:
          #sftp: false # optional
          host: ${{ secrets.FTP_HOST }} # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
          #port: 21 # optional, default is: 21
          username: ${{ secrets.FTP_USERNAME }} # FTP username
          password: ${{ secrets.FTP_PASSWORD }} # FTP password
          #remote_folder: ${{ secrets.FTP_REMOTE_FOLDER }} # optional, remote path of your FTP server
          local_folder: .output # optional, local path, default is: dist
          cleanup: false # optional, remove existing files inside FTP remote folder
          include: '['.output', 'index.js']' # optional, e.g. '['dist']'
          exclude: '[]' # optional, e.g. '['node_modules/**', '.git/**', '*.env']'
          #pasive: true # optional