name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }} -a
      - name: Clonar repositorio
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }} -a
      - name: Instalar packages
        run: npm i
      - name: Building...
        run: npm run build
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }} -a
      - run: echo "Valor de SALUDO ${{ secrets.SALUDO }}"

      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "index.js"
          remoteDir: "."
          options: ""